# Generated by Django 6.0.6 on 2026-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pray',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
